version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
  build:
    commands:
      - echo Running build...
      - echo Build started on `date`
  post_build:
    commands:
      - echo Tests completed on `date`

cache:
  paths:
    - '/root/.npm/**/*'
# version: 0.2

# phases:
#   pre_build:
#     commands:
#       - echo Logging in to Amazon ECR...
#       - aws --version
#       - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/w0w2z2x4
#       # - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 012345678910.dkr.ecr.us-west-2.amazonaws.com
#       - REPOSITORY_URI=public.ecr.aws/w0w2z2x4/book
#       - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
#       - IMAGE_TAG=${COMMIT_HASH:=latest}
#   build:
#     commands:
#       - echo Build started on `date`
#       - echo Building the Docker image...
#       - docker build -t book .
#       # - docker build -t $REPOSITORY_URI:latest .
#       - docker tag book:latest public.ecr.aws/w0w2z2x4/book:latest
#       # - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
#   post_build:
#     commands:
#       - echo Build completed on `date`
#       - echo Pushing the Docker images...
#       - docker push public.ecr.aws/w0w2z2x4/book:latest
#       # - docker push $REPOSITORY_URI:latest
#       - docker push public.ecr.aws/w0w2z2x4/book:$IMAGE_TAG
#       # - docker push $REPOSITORY_URI:$IMAGE_TAG
#       - echo Writing image definitions file...
#       - printf '[{"name":"book","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
# artifacts:
#   files: imagedefinitions.json

#version: 0.2

# phases:
#   install:
#     runtime-versions:
#       nodejs: 12
#     commands:
#       - echo Installing test runner...
#   build:
#     commands:
#       - echo Running build...
#       - echo Build started on `date`
#   post_build:
#     commands:
#       - echo Tests completed on `date`

# cache:
#   paths:
#     - '/root/.npm/**/*'
